export const CHANGE_NAME_VALUE = "CHANGE_NAME_VALUE";
export const CHANGE_PASSWORD_VALUE = "CHANGE_PASSWORD_VALUE";
export const CHANGE_PASSWORD_CONF_VALUE = "CHANGE_PASSWORD_CONF_VALUE";
export const CHANGE_EMAIL_VALUE = "CHANGE_EMAIL_VALUE";